rootPath: "/app/mis/"
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,shutdown,info
spring:
  profiles:
    active: dev
  ds:
    jndi: java:jboss/datasources/ncldb
#    url: jdbc:oracle:thin:@10.1.9.178:2521/tncldb
#    cn: oracle.jdbc.OracleDriver
#    ur: ncl_apuser
#    pw: nclap123
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    generate-ddl: false
    #    hibernate:
    #      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        #        default_schema: "ncladmin"
        default_schema: "ncl_apuser"
        max_fetch_depth: 3
        jdbc:
          fetch_size: 50
          batch_size: 30
        show_sql: true
        format_sql: true
  log:
    path: "${rootPath}log"
  application:
    name: mis
    rec: true
    fsapSyncFg: true

server:
  port: 9080
  address: 0.0.0.0
  compression:
    enabled: true

grpc:
  server:
    port: 50001
    address: "0.0.0.0"
    corePoolSize: 50
    maxPoolSize: 200
    threadQueueSize: 200
#  serverSecLi:
#    - port: 50001
#      address: "0.0.0.0"
#    - port: 50002
#      address: "0.0.0.0"
  runtime:
    port: 50002
    address: "10.1.11.32"
  common:
    port: 50002
    address: "10.1.11.32"

batch:
  name: mis
  corePoolSize: 25
  maxPoolSize: 100
  threadQueueSize: 100

fsap:
  client:
    enable:
      register: false
      eureka: false
  server:
    monitor:
      location: "http://10.1.7.206:8761/fsap-service-monitor/eureka/,http://10.1.7.207:8083/fsap-service-monitor/eureka/"

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true

astar:
  binPath: "${rootPath}astar/"

request:
  FD: "${rootPath}FD/"

apiNodes: >
  apiNode_ANALY_S00.yml,
  apiNode_ANALY_S02.yml,
  apiNode_ANALY_S03.yml,
  apiNode_ANALY_S04.yml,
  apiNode_ANALY_S05.yml,
  apiNode_ANALY_S06.yml,
  apiNode_ANALY_S07.yml,
  apiNode_ANALY_S08.yml,
  apiNode_ANALY_S19.yml,
  apiNode_ANALY_S21.yml,
  apiNode_ANALY_S22.yml,
  apiNode_ANALY_S23.yml,
  apiNode_BT002.yml,
  apiNode_C0760.yml,
  apiNode_C1530_S01.yml,
  apiNode_C1530_S02.yml,
  apiNode_C1530_S03_01.yml,
  apiNode_C1530_S03_02.yml,
  apiNode_C1530_S04_01.yml,
  apiNode_C1530_S04_02.yml,
  apiNode_C1530_S05.yml,
  apiNode_C1530_S06.yml,
  apiNode_C1530_S07.yml,
  apiNode_C1530_S08.yml,
  apiNode_C1530_S09.yml,
  apiNode_C1530_S10.yml,
  apiNode_C1530_S11.yml,
  apiNode_C1530_S12.yml,
  apiNode_C1530_S13.yml,
  apiNode_C1530_S14.yml,
  apiNode_C1530_S25.yml,
  apiNode_C1530_S42.yml,
  apiNode_C1530_S43.yml,
  apiNode_C1530_S45.yml,
  apiNode_C1530_S46_01.yml,
  apiNode_C1530_S46_02.yml,
  apiNode_C1530_S46_03.yml,
  apiNode_C1530_S46_04.yml,
  apiNode_C1530_S46_05.yml,
  apiNode_C1530_S49.yml,
  apiNode_C1530_S50_01.yml,
  apiNode_C1530_S50_02.yml,
  apiNode_C1530_S50_03.yml,
  apiNode_C1530_S55.yml,
  apiNode_C1530_S56.yml,
  apiNode_C1530_S57.yml,
  apiNode_C1530_S58.yml,
  apiNode_C1530_S85_01.yml,
  apiNode_C1530_S85_05.yml,
  apiNode_C1530_S86.yml,
  apiNode_C1530_S87.yml,
  apiNode_C1530_S89.yml,
  apiNode_C1530_S90.yml,
  apiNode_C1530_S91_01.yml,
  apiNode_C1530_S91_02.yml,
  apiNode_C1530_S91_03.yml,
  apiNode_CLADD.yml,
  apiNode_CLCMP.yml,
  apiNode_CLD03_S01.yml,
  apiNode_CLD03_S02.yml,
  apiNode_CLD03_S03.yml,
  apiNode_CLD04_S01.yml,
  apiNode_CLD04_S02.yml,
  apiNode_CLD11_S01.yml,
  apiNode_CLD12_S02.yml,
  apiNode_CLD12_S04.yml,
  apiNode_CLD20_S00.yml,
  apiNode_CLD22_S02.yml,
  apiNode_CLD22_S03.yml,
  apiNode_CLD22_S05.yml,
  apiNode_CLD22_S06.yml,
  apiNode_CLD22_S07.yml,
  apiNode_CLD23_S00.yml,
  apiNode_CLDTL_DWL.yml,
  apiNode_CLM01_S01.yml,
  apiNode_CLM01_S02.yml,
  apiNode_CLU01_S01.yml,
  apiNode_CLU01_S02.yml,
  apiNode_CLU01_S03.yml,
  apiNode_CONV27_S01.yml,
  apiNode_CONV27_S03.yml,
  apiNode_G2660.yml,
  apiNode_PRERU.yml,
  apiNode_PRETRUST_S01.yml,
  apiNode_PRETRUST_S02.yml,
  apiNode_STAT6_1B.yml,
  apiNode_STAT6_1C.yml,
  apiNode_STAT6_2A.yml,
  apiNode_STAT6_2B1.yml,
  apiNode_STAT6_2B2.yml,
  apiNode_STAT6_2C.yml,
  apiNode_STAT6_2D.yml,
  apiNode_STAT6_3A.yml,
  apiNode_STAT6_3B.yml,
  apiNode_STAT6_3C.yml,
  apiNode_STAT6_3F.yml,
  apiNode_STAT6_4A.yml,
  apiNode_STAT6_4B.yml,
  apiNode_STAT6_5.yml,
  apiNode_STAT6_5A.yml,
  apiNode_STAT6_5B.yml,
  apiNode_STAT6_5C.yml,
  apiNode_STAT6_5D.yml,
  apiNode_STAT6_5E.yml,
  apiNode_STAT6_6A.yml,
  apiNode_STAT6_6B2.yml,
  apiNode_STAT6_7A1.yml,
  apiNode_STAT6_7A2.yml,
  apiNode_STAT6_7A3.yml,
  apiNode_STAT6_7B1.yml,
  apiNode_STAT6_7B2.yml,
  apiNode_STAT6_7B3.yml,
  apiNode_STAT6_OKRTN.yml,
  apiNode_TXTEST.yml,
  apiNode_UPDCLCMP_S01.yml,
  apiNode_UPDCLCMP_S02.yml,
  apiNode_UPDCLCMP_S03.yml,
  apiNode_UPDCLCMP_S04.yml,
  apiNode_UPDCLCMP_S05.yml

localFile:
  ncl:
    batch:
      directory: "${rootPath}BH/"

fsapFile:
  gn:
    dwl:
      directory: "${rootPath}GN/DWL/"

externalSort:
  blockSize: 100000